# ~/resourcequota-with-object-count.yaml

apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resourcequota

spec:
  hard:
    cpu: "1000"
    memory: 200Gi
    pods: "10"
  requests.cpu: "1000m"
  requests.memory: "1Gi"
  limits.cpu: "2000m"
  limits.memory: "2Gi"
  configmaps: "10"
  services: "5"