apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: myrole
  namespace: dev

rules:
  - apiGroups: ["","extensions","apps"]
    resources: ["pods"]
    verbs: ["get","list","watch"]
    
    