apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
subjects:
  - kind: User
    name: Someuser # user name
    apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: myrole