# This is a sample pod definition for using SecretProviderClass and aad-pod-identity to access the key vault
apiVersion: v1
kind: Namespace
metadata:
  name:  csi

---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-podid
  namespace: csi
  labels:
    aadpodidbinding: myaks-id                   # Set the label value to the name of your pod identity
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name:  secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aks-kv-spc"