apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-kv-spc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"               # Set to true for using aad-pod-identity to access your key vault
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d7b163a5-41f1-4b84-b7b0-97137b7edb31
    keyvaultName:  myakskv2k8s       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: Secret1
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: Secret2
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""  
    tenantId: "b41b72d0-4e9f-4c26-8a69-f949f367c91d"                # The tenant ID of the key vault