apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-kv-spc
  namespace: csi
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: mykeyvault21970       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: aksSecret
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""  
        - |
          objectName: username
          objectType: secret             # object types: secret, key, or cert
          objectVersion: "" 
        - |
          objectName: password
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""             # [OPTIONAL] object versions, default to latest if empty
    tenantId: "b41b72d0-4e9f-4c26-8a69-f949f367c91d"                # The tenant ID of the key vault