apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        env:
          - name: host
            valueFrom:
              secretKeyRef:
                name: nginx-secret
                key: hostname

          - name: username
            valueFrom:
              secretKeyRef:
                name: nginx-secret
                key: username
          - name: pass
            valueFrom:
              secretKeyRef:
                name: nginx-secret
                key: password